// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/auth/login.post').default>>>>
    }
    '/api/admin/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/auth/register.post').default>>>>
    }
    '/api/admin/restaurants/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/restaurants/[id]/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/restaurants/[id]/index.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/restaurants/[id]/index.patch').default>>>>
    }
    '/api/admin/restaurants': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/restaurants/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/restaurants/index.post').default>>>>
    }
    '/api/public/menu': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/menu.get').default>>>>
    }
    '/api/public/orders': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/orders.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}