// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13.03.2026, 16:55:48
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/user/Desktop/Practrices/food-menu/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food-menu/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food-menu/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food-menu/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food-menu/app/plugins/**/*.{js,ts,mjs}","C:/Users/user/Desktop/Practrices/food-menu/app/composables/**/*.{js,ts,mjs}","C:/Users/user/Desktop/Practrices/food-menu/app/utils/**/*.{js,ts,mjs}","C:/Users/user/Desktop/Practrices/food-menu/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food-menu/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food-menu/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;