// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 08.09.2026, 15:24:37
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Leonid/Desktop/Projects/food-menu/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Leonid/Desktop/Projects/food-menu/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Leonid/Desktop/Projects/food-menu/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Leonid/Desktop/Projects/food-menu/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Leonid/Desktop/Projects/food-menu/app/plugins/**/*.{js,ts,mjs}","C:/Users/Leonid/Desktop/Projects/food-menu/app/composables/**/*.{js,ts,mjs}","C:/Users/Leonid/Desktop/Projects/food-menu/app/utils/**/*.{js,ts,mjs}","C:/Users/Leonid/Desktop/Projects/food-menu/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Leonid/Desktop/Projects/food-menu/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Leonid/Desktop/Projects/food-menu/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Leonid/Desktop/Projects/food-menu/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;