// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04.03.2026, 16:22:44
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/user/Desktop/Practrices/food/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food/app/plugins/**/*.{js,ts,mjs}","C:/Users/user/Desktop/Practrices/food/app/composables/**/*.{js,ts,mjs}","C:/Users/user/Desktop/Practrices/food/app/utils/**/*.{js,ts,mjs}","C:/Users/user/Desktop/Practrices/food/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/Practrices/food/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;